create table wdt_order_goods_202604
(
    id                bigint auto_increment
        primary key,
    rec_id            int            null comment 'erp子订单主键',
    trade_id          varchar(40)    not null comment 'erp订单表的主键',
    trade_time        datetime       not null comment '下单时间  时间格式：yyyy-MM-dd HH:mm:ss',
    spec_id           int            null comment 'erp内商品主键',
    platform_id       smallint       null comment '平台ID',
    src_oid           varchar(40)    not null comment '原始子订单号',
    platform_goods_id varchar(40)    null comment '平台货品ID',
    platform_spec_id  varchar(40)    null comment '平台商品ID',
    suite_id          int            null comment '组合装ID:如果货品是由组合装拆分的，这里组合装ID',
    flag              int            null comment '区分子单拆分的唯一性标记',
    src_tid           varchar(40)    null comment '原始订单号',
    gift_type         tinyint        null comment '赠品方式: 0非赠品 1自动赠送 2手工赠送 3回购自动送赠品  4前N有礼送赠品 6天猫优仓赠品 7淘宝CRM会员送赠',
    refund_status     tinyint        null comment '退款状态 0无退款,1取消退款,2已申请退款,3等待退货,4等待收货,5退款成功 6已关闭',
    guarantee_mode    tinyint        null comment '担保方式 1担保 2非担保 3在线非担保',
    delivery_term     tinyint        null comment '发货条件 1款到发货 2货到付款(包含部分货到付款) 3分期付款',
    bind_oid          varchar(40)    null comment '关联发货',
    num               decimal(19, 4) null comment '货品数量',
    price             decimal(19, 4) null comment '标价:销售单价，手工新建时使用货品属性中的“零售价”',
    actual_num        decimal(19, 4) null comment '实发数量,此数量为发货数量,删除操作等于将此值设置为0',
    refund_num        decimal(19, 4) null comment '无实际含义',
    order_price       decimal(19, 4) null comment '成交价,原始单折扣及分摊之后的价格',
    share_price       decimal(19, 4) null comment '分摊后价格:进入ERP后再次调整的价格，默认值与order_price一致',
    adjust            decimal(19, 4) null comment '手工调整价,正数为加价,负数为减价',
    discount          decimal(19, 4) null comment '总折扣金额',
    share_amount      decimal(19, 4) null comment '分摊后总价:分摊后合计应收=share_price * num , share_price 是根据share_amount反推的,因此share_price可能有精度损失',
    share_post        decimal(19, 4) null comment '分摊邮费',
    paid              decimal(19, 4) null comment '已支付金额',
    goods_name        varchar(255)   null comment '货品名称',
    class_name        varchar(32)    null comment '分类名称',
    prop2             varchar(255)   null comment '自定义属性2',
    tc_order_id       varchar(40)    null comment '分销商id',
    barcode           varchar(40)    null comment '主条码',
    goods_id          int            null comment '货品id',
    goods_no          varchar(40)    not null comment '货品编号:代表货品(spu) 所有属性的唯一编号，用于系统货品区分，，SPU概念介绍单击这里',
    spec_name         varchar(100)   null comment '规格名',
    spec_no           varchar(40)    not null comment '商家编码:代表单品(sku) 所有属性的唯一编码，用于系统单品区分，SKU概念介绍,单击这里',
    spec_code         varchar(40)    null comment '规格码',
    suite_no          varchar(40)    null comment '组合装编码:代表组合装商品所有属性的唯一编码，用于系统组合装商品的区分',
    suite_name        varchar(255)   null comment '拆自组合装:如果是组合装拆分的，此为组合装名称',
    suite_num         decimal(19, 4) null comment '组合装数量',
    suite_amount      decimal(19, 4) null comment '组合装分摊后总价',
    suite_discount    decimal(19, 4) null comment '组合装优惠',
    share_amount2     tinyint        null comment '是否打印组合装:0:组合装明细 1:组合装以及明细 2:组合装',
    is_print_suite    tinyint        null comment '是否打印组合装:0:组合装明细/ 1:组合装以及明细/ 2:组合装',
    is_zero_cost      tinyint(1)     null comment '是否允许0成本',
    stock_reserved    tinyint        null comment '库存保留情况',
    is_consigned      tinyint        null comment '平台已发货',
    is_received       tinyint        null comment '是否打款',
    is_master         tinyint(1)     null comment '是否为主子订单',
    api_goods_name    varchar(255)   null comment '平台货品名称',
    api_spec_name     varchar(100)   null comment '平台规格名称',
    weight            decimal(19, 4) null comment '预估单个货品重量（单位：kg）',
    commission        decimal(19, 4) null comment '佣金',
    goods_type        tinyint        null comment '货品类别',
    large_type        tinyint(1)     null comment '大件类型',
    invoice_type      tinyint        null comment '发票类别',
    invoice_content   varchar(255)   null comment '发票内容',
    from_mask         int            null comment '原始单标记',
    cid               int            null comment '类目id',
    remark            varchar(1024)  null comment '备注',
    modified          datetime       null comment '最后修改时间   时间格式：yyyy-MM-dd HH:mm:ss',
    created           datetime       null comment '创建时间   时间格式：yyyy-MM-dd HH:mm:ss',
    tax_rate          decimal(8, 4)  null comment '税率',
    base_unit_id      smallint       null comment '基本单位',
    unit_name         varchar(20)    null comment '基本单位名称',
    pay_id            varchar(40)    null comment '交易流水单号',
    pay_status        tinyint        null comment '子单付款状态',
    pay_time          varchar(20)    null comment '子单付款时间',
    trade_date        date           null comment '交易日期，格式：YYYY-MM-DD',
    shop_id           int            null comment '店铺ID'
)
    comment '旺店通订单商品表' row_format = DYNAMIC;


create table wdt_order_goods
(
    id                bigint auto_increment
        primary key,
    rec_id            int            null comment 'erp子订单主键',
    trade_id          varchar(40)    not null comment 'erp订单表的主键',
    trade_time        datetime       not null comment '下单时间  时间格式：yyyy-MM-dd HH:mm:ss',
    spec_id           int            null comment 'erp内商品主键',
    platform_id       smallint       null comment '平台ID',
    src_oid           varchar(40)    not null comment '原始子订单号',
    platform_goods_id varchar(40)    null comment '平台货品ID',
    platform_spec_id  varchar(40)    null comment '平台商品ID',
    suite_id          int            null comment '组合装ID:如果货品是由组合装拆分的，这里组合装ID',
    src_tid           varchar(40)    null comment '原始订单号',
    gift_type         tinyint        null comment '赠品方式: 0非赠品 1自动赠送 2手工赠送 3回购自动送赠品  4前N有礼送赠品 6天猫优仓赠品 7淘宝CRM会员送赠',
    refund_status     tinyint        null comment '退款状态 0无退款,1取消退款,2已申请退款,3等待退货,4等待收货,5退款成功 6已关闭',
    num               decimal(19, 4) null comment '货品数量',
    price             decimal(19, 4) null comment '标价:销售单价，手工新建时使用货品属性中的“零售价”',
    actual_num        decimal(19, 4) null comment '实发数量,此数量为发货数量,删除操作等于将此值设置为0',
    refund_num        decimal(19, 4) null comment '无实际含义',
    order_price       decimal(19, 4) null comment '成交价,原始单折扣及分摊之后的价格',
    share_price       decimal(19, 4) null comment '分摊后价格:进入ERP后再次调整的价格，默认值与order_price一致',
    adjust            decimal(19, 4) null comment '手工调整价,正数为加价,负数为减价',
    discount          decimal(19, 4) null comment '总折扣金额',
    share_amount      decimal(19, 4) null comment '分摊后总价:分摊后合计应收=share_price * num , share_price 是根据share_amount反推的,因此share_price可能有精度损失',
    share_post        decimal(19, 4) null comment '分摊邮费',
    paid              decimal(19, 4) null comment '已支付金额',
    goods_name        varchar(255)   null comment '货品名称',
    goods_id          int            null comment '货品id',
    goods_no          varchar(40)    not null comment '货品编号:代表货品(spu) 所有属性的唯一编号，用于系统货品区分，，SPU概念介绍单击这里',
    spec_name         varchar(100)   null comment '规格名',
    spec_no           varchar(40)    not null comment '商家编码:代表单品(sku) 所有属性的唯一编码，用于系统单品区分，SKU概念介绍,单击这里',
    spec_code         varchar(40)    null comment '规格码',
    suite_no          varchar(40)    null comment '组合装编码:代表组合装商品所有属性的唯一编码，用于系统组合装商品的区分',
    suite_name        varchar(255)   null comment '拆自组合装:如果是组合装拆分的，此为组合装名称',
    suite_num         decimal(19, 4) null comment '组合装数量',
    suite_amount      decimal(19, 4) null comment '组合装分摊后总价',
    suite_discount    decimal(19, 4) null comment '组合装优惠',
    is_print_suite    tinyint        null comment '是否打印组合装:0:组合装明细/ 1:组合装以及明细/ 2:组合装',
    api_goods_name    varchar(255)   null comment '平台货品名称',
    api_spec_name     varchar(100)   null comment '平台规格名称',
    weight            decimal(19, 4) null comment '预估单个货品重量（单位：kg）',
    cid               int            null comment '类目id',
    modified          datetime       null comment '最后修改时间   时间格式：yyyy-MM-dd HH:mm:ss',
    created           datetime       null comment '创建时间   时间格式：yyyy-MM-dd HH:mm:ss'
)
    comment '旺店通订单商品表' row_format = DYNAMIC;

create table wdt_platform
(
    id          bigint                                                           not null comment '平台ID',
    name        varchar(40)                                                      not null comment '平台名称',
    sort        bigint                                 default 0                 not null comment '显示排序',
    status      bigint                                 default 1                 not null comment '状态，1:启用 0:禁用',
    remark      varchar(255)                                                     null comment '说明',
    tenant_id   bigint                                 default 0                 not null comment '租户编号',
    creator     varchar(64) collate utf8mb4_unicode_ci default ''                null comment '创建者',
    create_time datetime                               default CURRENT_TIMESTAMP not null comment '创建时间',
    updater     varchar(64) collate utf8mb4_unicode_ci default ''                null comment '更新者',
    update_time datetime                               default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    deleted     bit                                    default b'0'              not null comment '是否删除',
    primary key (id, name)
);

create table wdt_shop
(
    platform_id     bigint                                                           not null comment '平台ID',
    platform_name   varchar(200)                                                     null comment '平台名称',
    sub_platform_id tinyint                                                          not null comment '子平台ID',
    shop_id         bigint                                                           not null comment '店铺列表主键'
        primary key,
    shop_no         varchar(20)                                                      not null comment '代表店铺所有属性的唯一编码，用于店铺区分，ERP内支持自定义（ERP店铺界面设置）',
    shop_name       varchar(256)                                                     not null comment 'ERP店铺界面的店铺名称',
    account_id      varchar(40)                                                      null comment '平台授权账号ID',
    account_nick    varchar(128)                                                     null comment '平台授权账号昵称',
    province        int                                                              null comment 'ERP店铺设置中的省份ID',
    city            int                                                              null comment 'ERP店铺设置中的城市ID',
    district        int                                                              null comment 'ERP店铺设置中的区县ID',
    province_name   varchar(50)                                                      null comment 'ERP店铺设置中的省份名称信息',
    city_name       varchar(50)                                                      null comment 'ERP店铺设置中的城市名称信息',
    district_name   varchar(50)                                                      null comment 'ERP店铺设置中的区县名称信息',
    address         varchar(255)                                                     null comment 'ERP店铺设置中的地址信息',
    contact         varchar(32)                                                      null comment 'ERP店铺设置中的联系人信息',
    zip             varchar(16)                                                      null comment 'ERP店铺设置中的邮编信息',
    mobile          varchar(40)                                                      null comment 'ERP店铺设置中的手机信息',
    telno           varchar(40)                                                      null comment 'ERP店铺设置中的电话信息',
    remark          varchar(255)                                                     null comment 'ERP店铺设置中的备注信息',
    tenant_id       bigint                                 default 0                 not null comment '租户编号',
    creator         varchar(64) collate utf8mb4_unicode_ci default ''                null comment '创建者',
    create_time     datetime                               default CURRENT_TIMESTAMP not null comment '创建时间',
    updater         varchar(64) collate utf8mb4_unicode_ci default ''                null comment '更新者',
    update_time     datetime                               default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    deleted         bit                                    default b'0'              not null comment '是否删除'
);

create table wdt_order_202604
(
    id                      bigint auto_increment
        primary key,
    trade_id                varchar(40)      null comment 'erp订单表的主键',
    trade_no                varchar(40)      not null comment '系统订单编号，默认单号为JY开头，ERP内支持自定义订单编号生成规则（设置路径：设置——编码设置）',
    platform_id             smallint         null comment '平台ID:响应值为代表平台的ID数字，ID对应的平台名称单击这里',
    shop_platform_id        smallint         null comment '店铺平台ID:响应值为代表平台的ID数字，ID对应的平台名称单击这里',
    shop_no                 varchar(20)      null comment '店铺编号:代表店铺所有属性的唯一编码，用于店铺区分，ERP内支持自定义（ERP店铺界面设置）',
    shop_name               varchar(200)     null comment '店铺名称',
    shop_remark             varchar(200)     null comment '店铺备注',
    warehouse_type          tinyint          null comment '仓库类型 （0不限 1普通仓库 2自动流传外部 3京东仓储 4科捷 5百世物流 6SKU360 7通天晓 8中联网仓 9顺丰仓储 10网仓2号 11奇门仓储 12旺店通仓储 13心怡仓储 14力威仓储 15京东沧海 16云集仓储 17POS 18虎符 20外部链路型 22抖店云仓 126分销委外仓 127其它）',
    warehouse_no            varchar(50)      null comment '仓库编号',
    src_tids                varchar(255)     null comment '原始单号:商城或电商平台的订单编号,合并订单的多个订单编号有逗号隔开',
    trade_status            tinyint          null comment '订单状态 5已取消 10待付款 12待尾款 13待选仓 15等未付16延时审核 19预订单前处理 20前处理(赠品，合并，拆分) 21委外前处理22抢单前处理 25预订单 27待抢单 30待客审 35待财审 40待递交仓库 45递交仓库中 50已递交仓库 53未确认 55已确认（已审核） 95已发货 105部分打款 110已完成 113异常发货',
    consign_status          int              null comment '出库状态：0表示无出库状态，1验货 2称重 4出库 8物流同步16分拣 32档口  64拣货 128供销回传成功  256供销回传失败（注意：如果是3，则表示完成了验货和称重“1+2”，如果是15，则表示四个过程都完成了“1+2+4+8”，其他数字以此类推）',
    trade_type              tinyint          null comment '订单类型:1网店销售 2线下零售 3售后换货 4批发业务 5保修换新 6保修完成 7订单补发 8供销补发   101自定义类型1 102自定义类型2 103自定义类型3 104自定义类型4 105自定义类型5 106自定义类型6 107自定义属性7 108自定义属性8',
    delivery_term           tinyint          null comment '发货条件 1款到发货 2货到付款(包含部分货到付款)，4挂账',
    freeze_reason           smallint         null,
    refund_status           tinyint          null comment '退款状态 0无退款 1申请退款 2部分退款 3全部退款 4未付款关闭或手工关闭 ',
    fenxiao_type            tinyint          null comment '分销类别 0非分销订单 1转供销 2代销 3经销',
    fenxiao_nick            varchar(40)      null comment '分销商信息:不同平台单据分销商会存不同格式情况，具体以返回信息为准',
    trade_time              datetime         not null comment '下单时间  时间格式：yyyy-MM-dd HH:mm:ss',
    pay_time                varchar(20)      null comment '付款时间  时间格式：yyyy-MM-dd HH:mm:ss',
    customer_name           varchar(200)     null comment '客户名称',
    customer_no             varchar(40)      null comment '客户编码',
    pay_account             varchar(200)     null comment '买家付款账号',
    buyer_nick              varchar(200)     null comment '客户网名',
    receiver_province       int              null comment '收件人的省份,按照城市代码表中对应城市代码进行返回',
    receiver_city           int              null comment '收件人的城市,按照城市代码表中对应城市代码进行返回',
    receiver_district       int              null comment '收件人的地区,按照城市代码表中对应城市代码进行返回',
    receiver_name           varchar(128)     null comment '收件人姓名',
    receiver_mobile         varchar(128)     null comment '收件人手机号',
    receiver_telno          varchar(100)     null comment '电话',
    receiver_zip            varchar(20)      null comment '收件人邮编',
    receiver_area           varchar(200)     null comment '省市县空格分隔',
    receiver_ring           varchar(20)      null comment '收件人区域',
    receiver_dtb            varchar(200)     null comment '大头笔',
    to_deliver_time         varchar(20)      null comment '派送时间',
    bad_reason              int              null comment '异常订单 2地址变化 8仓库变化 16客服备注变化 128拦截赠品 64退款 2048买家留言发生变更',
    logistics_id            bigint           null comment '物流公司ID',
    logistics_name          varchar(40)      null comment '物流公司名称',
    logistics_type          bigint           null comment '代表物流方式的数字',
    logistics_code          varchar(20)      null comment '代表物流所有属性的唯一编码',
    receiver_address_header varchar(128)     null comment '地址',
    receiver_address        varchar(256)     null comment '地址',
    logistics_no            varchar(40)      null comment '物流单号',
    shop_id                 smallint         null comment '店铺列表主键',
    check_step              tinyint          null comment '审核步骤 用于多级审核, 特殊值：-100根据预售策略自动转入特殊单，-101人工转入',
    unmerge_mask            tinyint          null comment '未合并标记,1有未付款订单,2有同名未合并订单',
    delay_to_time           varchar(11)      null comment '延迟处理 延时此进一步处理，等未付或延时审核 激活时间秒级时间戳格式返回',
    customer_type           tinyint          null comment '客户类型  0普通客户1经销商',
    pre_charge_time         varchar(20)      null comment '预配送时间',
    is_prev_notify          tinyint          null comment '是否京配(为1时, 只能发京邦达）',
    note_count              smallint         null comment '便签条数',
    buyer_message_count     tinyint          null comment '买家留言条数',
    cs_remark_count         tinyint          null comment '客服备注条数',
    cs_remark_change_count  smallint         null comment '客服备注变化',
    warehouse_id            bigint           null comment '仓库id',
    customer_id             varchar(11)      null comment '买家ID',
    receiver_country        smallint         null comment '收件人国家',
    discount_change         decimal(19, 4)   null comment '优惠变化金额,更新货品和数量',
    trade_prepay            decimal(19, 4)   null comment '使用的预存款',
    pi_amount               decimal(19, 4)   null comment '分期付款金额',
    other_cost              decimal(19, 4)   null comment '其它成本',
    volume                  decimal(19, 4)   null comment '体积',
    sales_score             varchar(11)      null comment '销售积分',
    flag_id                 smallint         null comment '标记id',
    is_sealed               tinyint(1)       null comment '不可合并拆分',
    gift_mask               tinyint          null comment '赠品标记1已处理过赠品,但没有匹配任何策略2自动赠送4手工赠送6即有自动也有手工',
    split_from_trade_id     varchar(11)      null comment '拆分订单，原单ID，用于避免自动合并,大件拆分为（原订单的id值），自动拆分为负值（原订单的-id值）',
    logistics_template_id   varchar(11)      null comment '物流单模板ID',
    sendbill_template_id    varchar(11)      null comment '发货单模板id',
    revert_reason           smallint         null comment '驳回原因',
    cancel_reason           smallint         null comment '取消原因',
    is_unpayment_sms        tinyint(1)       null comment '催未付款订单消息发送标记',
    package_id              varchar(11)      null comment '包装id',
    trade_mask              varchar(11)      null comment '订单标记位',
    reserve                 varchar(40)      null comment '保留',
    large_type              tinyint          null comment '大件类型',
    buyer_message           varchar(1024)    null comment '买家留言',
    cs_remark               varchar(1024)    null comment '客服备注',
    remark_flag             tinyint          null comment '标旗',
    print_remark            varchar(255)     null comment '打印备注',
    goods_type_count        smallint         null comment '货品种类数',
    goods_count             decimal(19, 4)   null comment '货品总数',
    goods_amount            decimal(19, 4)   null comment '货品总额（未扣除优惠），sum（share_amount+discount）所得',
    post_amount             decimal(19, 4)   null comment '邮资',
    other_amount            decimal(19, 4)   null comment '其它费用',
    discount                decimal(19, 4)   null comment '订单优惠，系统子订单“优惠”求合所得',
    receivable              decimal(19, 4)   null comment '应收金额，系统订单的（“货品总额”+“邮资”-“折扣”）所得',
    dap_amount              decimal(19, 4)   null comment '款到发货金额,paid>=dap_amount才可发货',
    cod_amount              decimal(19, 4)   null comment '货到付款订单金额，系统子订单的（“分摊后总价”+“分摊邮费”-“已付”）再求和',
    ext_cod_fee             decimal(19, 4)   null comment '货到付款非订单金额，从原始订单继承',
    goods_cost              decimal(19, 4)   null comment '货款预估成本',
    post_cost               decimal(19, 4)   null comment '预估邮费成本',
    paid                    decimal(19, 4)   null comment '已付金额，系统子订单“已付”求合所得',
    weight                  decimal(19, 4)   null comment '预估重量（单位：kg）',
    profit                  decimal(19, 4)   null comment '预估毛利',
    tax                     decimal(19, 4)   null comment '税额',
    tax_rate                decimal(19, 4)   null comment '税率',
    commission              decimal(19, 4)   null comment '佣金',
    invoice_type            tinyint          null comment '发票类型',
    invoice_title           varchar(255)     null comment '发票抬头',
    invoice_content         varchar(255)     null comment '发票内容',
    salesman_id             int              null comment '业务员',
    checker_id              int              null comment '审核人',
    fullname                varchar(40)      null comment '业务员姓名',
    checker_name            varchar(40)      null comment '审核人',
    fchecker_id             int              null comment '财审人',
    checkouter_id           int              null comment '签出人',
    stockout_no             varchar(40)      null comment '出库单号,内部或外部仓库的订单号',
    flag_name               varchar(40)      null comment '标记名称',
    trade_from              tinyint(1)       null comment '订单来源',
    single_spec_no          varchar(40)      null comment '货品商家编码',
    raw_goods_count         decimal(19, 4)   null comment '原始货品数量',
    raw_goods_type_count    int              null comment '原始货品种类数',
    currency                varchar(20)      null comment '币种',
    split_package_num       int              null comment '线上包裹拆分数',
    invoice_id              int              null comment '发票ID',
    version_id              smallint         null comment '订单每修改一次，版本号做一次变更',
    modified                datetime         null comment '最后修改时间   时间格式：yyyy-MM-dd HH:mm:ss',
    created                 datetime         null comment '系统单生成时间   时间格式：yyyy-MM-dd HH:mm:ss',
    id_card_type            tinyint          null comment '证件类别',
    id_card                 varchar(40)      null comment '证件号码',
    fchecker_name           varchar(40)      null comment '财审人名称',
    checkouter_name         varchar(40)      null comment '签出人名称',
    freeze_reason_info      varchar(40)      null comment '冻结原因名称',
    fenxiao_tid             varchar(255)     null comment '分销原始单号',
    tags                    varchar(1024)    null comment '订单标签/异常',
    fenxiao_id              varchar(40)      null comment '分销id',
    fenxiao_name            varchar(140)     null comment '分销名称',
    dept_type               int default 0    not null comment '部门:1-直播部,2-达播部',
    deleted                 bit default b'0' not null comment '是否删除',
    trade_date              date             null comment '交易日期，格式：YYYY-MM-DD'
)
    comment '旺店通订单表' row_format = DYNAMIC;

create table wdt_refund
(
    id                     bigint auto_increment comment '主键'
        primary key,
    refund_id              int            null comment '退换单主键',
    refund_no              varchar(40)    null comment 'erp退换单号，默认TK开头',
    api_outer_no           varchar(40)    null comment '接口创建退换单的外部单号',
    platform_id            int            null comment '平台类型，响应值为代表平台的ID数字',
    src_no                 varchar(40)    null comment '平台退款单号(若erp上退换单平台单号为空，返回空)',
    type                   int            null comment '类型:1退款(未发货，退款申请)2退货3换货4退款不退货5订单补款',
    process_status         int            null comment '处理状态:10已取消 15审核前处理 20待审核 30已审核 40已拒绝 52逆向待推送  54逆向推送失败 55待筛单  56不可达  58代取件  59取件失败  60待收货 63待推送 64推送失败 65委外待收货 70部分到货  80待结算 90已完成',
    status                 int            null comment '平台状态 0表示为空，1取消退款，2已申请退款，3等待退货，4等待收货，5退款成功，10换货待处理，20待买家退货，30买家已退货 待收货，40待买家修改，50待发出换货商品，55待买家收货，60换货改退货，70换货关闭，80换货成功',
    guarantee_mode         int            null comment '担保方式1担保交易2非担保交易3非担保在线交易（ecshop）',
    cs_status              int            null comment '退款阶段  0售中 1售后',
    shop_no                varchar(20)    null comment '店铺编号 代表店铺所有属性的唯一编码，用于店铺区分，ERP内支持自定义（ERP店铺界面设置）',
    swap_trade_id          int            null comment '换出原始单id',
    pay_account            varchar(128)   null comment '买家支付帐号',
    pay_no                 varchar(60)    null comment '支付订单号',
    goods_amount           decimal(20, 4) null comment '退货金额',
    refund_amount          decimal(20, 4) null comment '买家申请退款金额',
    direct_refund_amount   decimal(20, 4) null comment '线下退款金额 订单确认收货之后的退款金额',
    guarante_refund_amount decimal(20, 4) null comment '平台退款金额',
    actual_refund_amount   decimal(20, 4) null comment '实际退款/收款金额',
    exchange_amount        decimal(20, 4) null comment '换货金额',
    post_amount            decimal(20, 4) null comment '邮费金额',
    other_amount           decimal(20, 4) null comment '其它金额',
    paid                   decimal(20, 4) null comment '已退款/已收款',
    tid                    varchar(500)   null comment '订单的原始单号',
    sales_trade_id         int            null comment '系统订单ID',
    sales_tid              varchar(40)    null comment '系统订单编号，默认单号为JY开头，ERP内支持自定义（设置路径：设置——编码设置）',
    buyer_nick             varchar(100)   null comment '昵称',
    receiver_name          varchar(40)    null comment '收件人姓名',
    receiver_address       varchar(255)   null comment '收件人地址',
    receiver_telno         varchar(255)   null comment '收件人电话',
    return_name            varchar(40)    null comment '退货人姓名',
    return_mobile          varchar(40)    null comment '退货人手机号',
    return_telno           varchar(100)   null comment '退货人电话',
    return_address         varchar(255)   null comment '退回仓库地址',
    return_logistics_name  varchar(40)    null comment '退回物流公司名称',
    return_logistics_no    varchar(100)   null comment '退回物流单号',
    swap_receiver          varchar(40)    null comment '换货收件人姓名',
    swap_mobile            varchar(40)    null comment '换收发件人姓名手机',
    swap_telno             varchar(100)   null comment '换货收件人姓名电话',
    swap_province          int            null comment '换货收件人省份',
    swap_city              int            null comment '换货收件人城市',
    swap_district          int            null comment '换货收件人区县',
    swap_area              varchar(40)    null comment '换货收件人省市区',
    swap_warehouse_no      varchar(40)    null comment '换出货品出库仓库编号',
    swap_address           varchar(255)   null comment '换货收件人姓名地址',
    warehouse_no           varchar(40)    null comment '期望退回的仓库编号',
    refund_time            varchar(100)   null comment '退款创建时间  格式：yyyy-MM-dd HH:mm:ss',
    remark                 varchar(500)   null comment '备注',
    refund_reason          varchar(500)   null comment '退款的具体原因说明',
    swap_trade_no          varchar(40)    null comment 'ERP生成的换出订单的原始订单编号',
    modified               datetime       null comment '最后修改时间  格式：yyyy-MM-dd HH:mm:ss',
    finish_time            varchar(100)   null comment '旺店通内操作结算的时间  格式：yyyy-MM-dd HH:mm:ss',
    customer_no            varchar(40)    null comment '客户档案编号',
    customer_name          varchar(40)    null comment '收件人姓名（如需唯一值，以receiver_name为准）',
    swap_zip               varchar(20)    null comment '收件人邮编',
    swap_logistics_type    int            null comment '换货新订单物流公司类别',
    swap_logistics_name    varchar(40)    null comment '换货新订单物流公司名称',
    creator_name           varchar(40)    null comment '建单员姓名',
    error_msg              varchar(255)   null comment '逆向物流错误信息',
    created                datetime       null comment '创建时间',
    outer_no               varchar(40)    null comment '外部编号 默认为''''，外部编号,与wms对接使用',
    shop_name              varchar(200)   null comment '店铺名称',
    warehouse_id           int            null comment '仓库id 默认为''0''，期望退回的仓库',
    shop_id                int            null comment '店铺id',
    advance_status         int            null comment '预先状态 默认为''0''，0; 退款先行垫付申请 1; 退款先行垫付，垫付完成 2; 退款先行垫付，卖家拒绝收货 3; 退款先行垫付，垫付关闭 4; 退款先行垫付，垫付分账成功 5;',
    is_goods_received      int            null comment '是否收到货品 默认为''0''，买家是否收到货',
    customer_id            int            null comment '客户id 默认为''0''，客户id',
    tags                   text           null comment '订单标签/异常id，具体标签/异常名称查询',
    swap_warehouse_id      int            null comment '换出仓库id 默认为''0''，换出货品出库仓库',
    swap_logistics_id      int            null comment '换出物流id 默认为''0''，换货新订单物流公司ID',
    warehouse_type         int            null comment '仓库类型 默认为''0''，期望退回仓库类型（0不限 1普通仓库 2自动流传外部 3京东仓储 4科捷 5百世物流 6SKU360 7通天晓 8中联网仓 9顺丰仓储 10网仓2号 11奇门仓储 12旺店通仓储 13心怡仓储 14力威仓储 15京东沧海 16云集仓储 17POS 18虎符 20外部链路型 22抖店云仓 126分销委外仓 127其它）',
    wms_status             int            null comment 'wms状态 	默认为''0''，外部状态,与wms对接使用 0初始化 1失败 2成功',
    wms_result             varchar(255)   null comment 'wms结果 默认为''''，外部结果,与wms对接使用',
    wms_outer_no           varchar(40)    null comment '外部仓库的单号 默认为''''，对应外部仓库的单号',
    from_type              int            null comment '建立方式 	默认为''1''，建立方式 1api抓单 2手式建单 3外部导入 4天猫换货 5菜鸟回传自动创建',
    return_goods_count     decimal(40, 4) null comment '退回货品数量 默认为''0''，退回货品数量',
    op_constraint          int            null comment '约束 默认为''0''，1不允许拒绝2需要到网页版操作',
    refund_version         varchar(40)    null comment '退款版本 默认为''''，退款版本,大于0后表明已经从平台下载完成，退款单不可修改',
    consign_mode           int            null comment '发货方式 默认为''0''，发货方式：0默认 1审核退款单后立即生成换货订单 2退货完成后生成换货订单',
    logistics_name         varchar(40)    null comment '物流公司名称 默认为''''，物流公司名称',
    logistics_no           varchar(40)    null comment '物流单号 默认为''''，物流单号',
    push_no                varchar(50)    null comment '物流递交单号 默认为''''，物流递交单号',
    logistics_style        int            null comment '物流形式 默认为''0''，取件方式 :0客户取件，1顺丰取件，2拒收退回',
    reason_id              int            null comment '原因 默认为''0''，原因',
    revert_reason          int            null comment '驳回原因 默认为''0''，驳回原因',
    bad_reason             int            null comment '错误原因 默认为''0''，错误原因',
    return_mask            int            null comment '返回标志 默认为''0''，标志位 4-原始单唯一 8-增加退换在途量 16-确认退款金额标识(为了保持兼容，0表示已确认，1表示未确认) 32-对应订单是否开了电子发票 64天猫换货单关闭需要取消委外单 128天猫换货改退货需取消换出订单',
    is_trade_charged       int            null comment '是否结算后生成订单 默认为''0''，是否结算后生成订单',
    stockin_pre_no         varchar(40)    null comment '预入库单 默认为''''，预入库单',
    revert_reason_info     varchar(40)    null comment '驳回原因名称',
    fenxiao_nick_name      varchar(40)    null comment '分销商名称',
    fenxiao_refund_no      varchar(40)    null comment '分销商退换单号',
    fenxiao_tid            varchar(255)   null comment '分销原始单号',
    flag_name              varchar(40)    null comment '名称'
)
    comment '旺店通退换单';

create table wdt_district
(
    code int         not null comment '区县代码',
    name varchar(40) not null comment '区县名称',
    primary key (code, name)
);

create table wdt_order
(
    id                      bigint auto_increment
        primary key,
    trade_id                varchar(40)      null comment 'erp订单表的主键',
    trade_no                varchar(40)      not null comment '系统订单编号，默认单号为JY开头，ERP内支持自定义订单编号生成规则（设置路径：设置——编码设置）',
    platform_id             smallint         null comment '平台ID:响应值为代表平台的ID数字，ID对应的平台名称单击这里',
    shop_platform_id        smallint         null comment '店铺平台ID:响应值为代表平台的ID数字，ID对应的平台名称单击这里',
    shop_no                 varchar(20)      null comment '店铺编号:代表店铺所有属性的唯一编码，用于店铺区分，ERP内支持自定义（ERP店铺界面设置）',
    src_tids                varchar(255)     null comment '原始单号:商城或电商平台的订单编号,合并订单的多个订单编号有逗号隔开',
    trade_status            tinyint          null comment '订单状态 5已取消 10待付款 12待尾款 13待选仓 15等未付16延时审核 19预订单前处理 20前处理(赠品，合并，拆分) 21委外前处理22抢单前处理 25预订单 27待抢单 30待客审 35待财审 40待递交仓库 45递交仓库中 50已递交仓库 53未确认 55已确认（已审核） 95已发货 105部分打款 110已完成 113异常发货',
    consign_status          int              null comment '出库状态：0表示无出库状态，1验货 2称重 4出库 8物流同步16分拣 32档口  64拣货 128供销回传成功  256供销回传失败（注意：如果是3，则表示完成了验货和称重“1+2”，如果是15，则表示四个过程都完成了“1+2+4+8”，其他数字以此类推）',
    trade_type              tinyint          null comment '订单类型:1网店销售 2线下零售 3售后换货 4批发业务 5保修换新 6保修完成 7订单补发 8供销补发   101自定义类型1 102自定义类型2 103自定义类型3 104自定义类型4 105自定义类型5 106自定义类型6 107自定义属性7 108自定义属性8',
    refund_status           tinyint          null comment '退款状态 0无退款 1申请退款 2部分退款 3全部退款 4未付款关闭或手工关闭 ',
    fenxiao_nick            varchar(40)      null comment '分销商信息:不同平台单据分销商会存不同格式情况，具体以返回信息为准',
    trade_time              datetime         not null comment '下单时间  时间格式：yyyy-MM-dd HH:mm:ss',
    pay_time                varchar(20)      null comment '付款时间  时间格式：yyyy-MM-dd HH:mm:ss',
    customer_no             varchar(40)      null comment '客户编码',
    receiver_province       int              null comment '收件人的省份,按照城市代码表中对应城市代码进行返回',
    receiver_city           int              null comment '收件人的城市,按照城市代码表中对应城市代码进行返回',
    receiver_district       int              null comment '收件人的地区,按照城市代码表中对应城市代码进行返回',
    receiver_name           varchar(128)     null comment '收件人姓名',
    receiver_mobile         varchar(128)     null comment '收件人手机号',
    receiver_address_header varchar(128)     null comment '地址',
    receiver_address        varchar(256)     null comment '地址',
    logistics_no            varchar(40)      null comment '物流单号',
    shop_id                 smallint         null comment '店铺列表主键',
    customer_id             varchar(11)      null comment '买家ID',
    receiver_country        smallint         null comment '收件人国家',
    discount_change         decimal(19, 4)   null comment '优惠变化金额,更新货品和数量',
    gift_mask               tinyint          null comment '赠品标记1已处理过赠品,但没有匹配任何策略2自动赠送4手工赠送6即有自动也有手工',
    split_from_trade_id     varchar(11)      null comment '拆分订单，原单ID，用于避免自动合并,大件拆分为（原订单的id值），自动拆分为负值（原订单的-id值）',
    revert_reason           smallint         null comment '驳回原因',
    cancel_reason           smallint         null comment '取消原因',
    goods_type_count        smallint         null comment '货品种类数',
    goods_count             decimal(19, 4)   null comment '货品总数',
    goods_amount            decimal(19, 4)   null comment '货品总额（未扣除优惠），sum（share_amount+discount）所得',
    discount                decimal(19, 4)   null comment '订单优惠，系统子订单“优惠”求合所得',
    receivable              decimal(19, 4)   null comment '应收金额，系统订单的（“货品总额”+“邮资”-“折扣”）所得',
    dap_amount              decimal(19, 4)   null comment '款到发货金额,paid>=dap_amount才可发货',
    cod_amount              decimal(19, 4)   null comment '货到付款订单金额，系统子订单的（“分摊后总价”+“分摊邮费”-“已付”）再求和',
    ext_cod_fee             decimal(19, 4)   null comment '货到付款非订单金额，从原始订单继承',
    goods_cost              decimal(19, 4)   null comment '货款预估成本',
    post_cost               decimal(19, 4)   null comment '预估邮费成本',
    paid                    decimal(19, 4)   null comment '已付金额，系统子订单“已付”求合所得',
    weight                  decimal(19, 4)   null comment '预估重量（单位：kg）',
    stockout_no             varchar(40)      null comment '出库单号,内部或外部仓库的订单号',
    raw_goods_count         decimal(19, 4)   null comment '原始货品数量',
    raw_goods_type_count    int              null comment '原始货品种类数',
    version_id              smallint         null comment '订单每修改一次，版本号做一次变更',
    modified                datetime         null comment '最后修改时间   时间格式：yyyy-MM-dd HH:mm:ss',
    created                 datetime         null comment '系统单生成时间   时间格式：yyyy-MM-dd HH:mm:ss',
    fenxiao_id              varchar(40)      null comment '分销id',
    fenxiao_name            varchar(140)     null comment '分销名称',
    dept_type               int default 0    not null comment '部门:1-直播部,2-达播部',
    deleted                 bit default b'0' not null comment '是否删除'
)
    comment '旺店通订单表' row_format = DYNAMIC;

create table wdt_city
(
    code int         not null comment '城市代码',
    name varchar(40) not null comment '城市名称',
    primary key (code, name)
);

create table wdt_refund_order
(
    id                  bigint auto_increment comment '主键'
        primary key,
    order_id            int            null comment '退换单退回货品明细主键',
    refund_id           int            null comment '退换单主键',
    oid                 varchar(40)    null comment '原始子订单编号',
    tid                 varchar(40)    null comment '订单子订单的原始单号',
    src_no              varchar(40)    null comment '平台退款单号',
    process_status      int            null comment '处理状态:处理状态0已取消 10待递交 20待审核 30已同意 40已拒绝 50待财审 60待收货 70部分到货 80已完成(业务意义不完整，请使用refunds节点下的process_status)',
    sales_tid           varchar(40)    null comment '销售订单编号',
    order_num           decimal(20, 4) null comment '实际数量',
    price               decimal(20, 4) null comment '价格',
    platform_id         int            null comment '平台类型，响应值为代表平台的ID数字',
    cost_price          decimal(20, 4) null comment '成本价',
    original_price      decimal(20, 4) null comment '原价',
    discount            decimal(20, 4) null comment '优惠',
    paid                decimal(20, 4) null comment '已付金额',
    market_price        decimal(20, 4) null comment '单品市场价',
    refund_num          decimal(20, 4) null comment '退款数量',
    refund_order_amount decimal(20, 4) null comment '明细退款金额，由主单退款金额分摊',
    total_amount        decimal(20, 4) null comment '退货金额',
    spec_id             int            null comment 'erp商品主键',
    spec_no             varchar(40)    null comment '商家编码 	代表单品(sku)所有属性的唯一编码，用于系统单品区分',
    goods_name          varchar(255)   null comment '货品名称',
    goods_no            varchar(40)    null comment '货品编号',
    spec_name           varchar(100)   null comment '规格名称',
    spec_code           varchar(40)    null comment '规格编码',
    suite_no            varchar(40)    null comment '组合装编号',
    suite_name          varchar(255)   null comment '组合装名称',
    suite_num           decimal(20, 4) null comment '组合装数量',
    stockin_num         decimal(20, 4) null comment '退货入库数量',
    remark              varchar(255)   null comment '退换明细的备注',
    is_sn_enable        int            null comment '是否启用序列号 默认为''0''，0不启用序列号 1强序列号 2弱序列号',
    position_no         varchar(40)    null comment '货位编号',
    position_id         int            null comment '货位ID',
    sales_trade_id      int            null comment '系统订单ID',
    sales_order_id      int            null comment '销售订单ID 默认为''0''',
    goods_id            int            null comment '货品ID',
    suite_id            int            null comment '默认为''0''，组合装ID',
    stockin_amount      decimal(20, 4) null comment '退货入库总额',
    from_mask_ext       varchar(20)    null comment '平台标签  1集运订单(京东) 2小时达(淘宝) 4小时达平台运力(淘宝) 8以旧换新 16国补订单',
    modified            datetime       null comment '最后修改时间  格式：yyyy-MM-dd HH:mm:ss',
    created             datetime       null comment '创建时间',
    edit_mask           int            null comment '默认为''0''，编辑掩码',
    tag                 int            null comment '默认为''0''，标签',
    barcode             varchar(50)    null comment '主条码',
    brand_name          varchar(64)    null comment '品牌名称'
)
    comment '退款子订单信息';

create table wdt_order_no_route
(
    id                      bigint auto_increment
        primary key,
    trade_id                varchar(40)      null comment 'erp订单表的主键',
    trade_no                varchar(40)      not null comment '系统订单编号，默认单号为JY开头，ERP内支持自定义订单编号生成规则（设置路径：设置——编码设置）',
    platform_id             smallint         null comment '平台ID:响应值为代表平台的ID数字，ID对应的平台名称单击这里',
    shop_platform_id        smallint         null comment '店铺平台ID:响应值为代表平台的ID数字，ID对应的平台名称单击这里',
    shop_no                 varchar(20)      null comment '店铺编号:代表店铺所有属性的唯一编码，用于店铺区分，ERP内支持自定义（ERP店铺界面设置）',
    src_tids                varchar(255)     null comment '原始单号:商城或电商平台的订单编号,合并订单的多个订单编号有逗号隔开',
    trade_status            tinyint          null comment '订单状态 5已取消 10待付款 12待尾款 13待选仓 15等未付16延时审核 19预订单前处理 20前处理(赠品，合并，拆分) 21委外前处理22抢单前处理 25预订单 27待抢单 30待客审 35待财审 40待递交仓库 45递交仓库中 50已递交仓库 53未确认 55已确认（已审核） 95已发货 105部分打款 110已完成 113异常发货',
    consign_status          int              null comment '出库状态：0表示无出库状态，1验货 2称重 4出库 8物流同步16分拣 32档口  64拣货 128供销回传成功  256供销回传失败（注意：如果是3，则表示完成了验货和称重“1+2”，如果是15，则表示四个过程都完成了“1+2+4+8”，其他数字以此类推）',
    trade_type              tinyint          null comment '订单类型:1网店销售 2线下零售 3售后换货 4批发业务 5保修换新 6保修完成 7订单补发 8供销补发   101自定义类型1 102自定义类型2 103自定义类型3 104自定义类型4 105自定义类型5 106自定义类型6 107自定义属性7 108自定义属性8',
    refund_status           tinyint          null comment '退款状态 0无退款 1申请退款 2部分退款 3全部退款 4未付款关闭或手工关闭 ',
    fenxiao_nick            varchar(40)      null comment '分销商信息:不同平台单据分销商会存不同格式情况，具体以返回信息为准',
    trade_time              datetime         not null comment '下单时间  时间格式：yyyy-MM-dd HH:mm:ss',
    pay_time                varchar(20)      null comment '付款时间  时间格式：yyyy-MM-dd HH:mm:ss',
    customer_no             varchar(40)      null comment '客户编码',
    receiver_province       int              null comment '收件人的省份,按照城市代码表中对应城市代码进行返回',
    receiver_city           int              null comment '收件人的城市,按照城市代码表中对应城市代码进行返回',
    receiver_district       int              null comment '收件人的地区,按照城市代码表中对应城市代码进行返回',
    receiver_name           varchar(128)     null comment '收件人姓名',
    receiver_mobile         varchar(128)     null comment '收件人手机号',
    receiver_address_header varchar(128)     null comment '地址',
    receiver_address        varchar(256)     null comment '地址',
    logistics_no            varchar(40)      null comment '物流单号',
    shop_id                 smallint         null comment '店铺列表主键',
    customer_id             varchar(11)      null comment '买家ID',
    receiver_country        smallint         null comment '收件人国家',
    discount_change         decimal(19, 4)   null comment '优惠变化金额,更新货品和数量',
    gift_mask               tinyint          null comment '赠品标记1已处理过赠品,但没有匹配任何策略2自动赠送4手工赠送6即有自动也有手工',
    split_from_trade_id     varchar(11)      null comment '拆分订单，原单ID，用于避免自动合并,大件拆分为（原订单的id值），自动拆分为负值（原订单的-id值）',
    revert_reason           smallint         null comment '驳回原因',
    cancel_reason           smallint         null comment '取消原因',
    goods_type_count        smallint         null comment '货品种类数',
    goods_count             decimal(19, 4)   null comment '货品总数',
    goods_amount            decimal(19, 4)   null comment '货品总额（未扣除优惠），sum（share_amount+discount）所得',
    discount                decimal(19, 4)   null comment '订单优惠，系统子订单“优惠”求合所得',
    receivable              decimal(19, 4)   null comment '应收金额，系统订单的（“货品总额”+“邮资”-“折扣”）所得',
    dap_amount              decimal(19, 4)   null comment '款到发货金额,paid>=dap_amount才可发货',
    cod_amount              decimal(19, 4)   null comment '货到付款订单金额，系统子订单的（“分摊后总价”+“分摊邮费”-“已付”）再求和',
    ext_cod_fee             decimal(19, 4)   null comment '货到付款非订单金额，从原始订单继承',
    goods_cost              decimal(19, 4)   null comment '货款预估成本',
    post_cost               decimal(19, 4)   null comment '预估邮费成本',
    paid                    decimal(19, 4)   null comment '已付金额，系统子订单“已付”求合所得',
    weight                  decimal(19, 4)   null comment '预估重量（单位：kg）',
    stockout_no             varchar(40)      null comment '出库单号,内部或外部仓库的订单号',
    raw_goods_count         decimal(19, 4)   null comment '原始货品数量',
    raw_goods_type_count    int              null comment '原始货品种类数',
    version_id              smallint         null comment '订单每修改一次，版本号做一次变更',
    modified                datetime         null comment '最后修改时间   时间格式：yyyy-MM-dd HH:mm:ss',
    created                 datetime         null comment '系统单生成时间   时间格式：yyyy-MM-dd HH:mm:ss',
    fenxiao_id              varchar(40)      null comment '分销id',
    fenxiao_name            varchar(140)     null comment '分销名称',
    dept_type               int default 0    not null comment '部门:1-直播部,2-达播部',
    deleted                 bit default b'0' not null comment '是否删除',
    trade_date              date             null comment '交易日期，格式：YYYY-MM-DD'
)
    comment '旺店通订单表' row_format = DYNAMIC;

create table wdt_province
(
    code     int         not null comment '省份代码',
    name     varchar(40) not null comment '省份名称',
    iso_code char(5)     null comment 'iso编码',
    primary key (code, name)
);

create table wdt_order_fetch_log
(
    id             bigint auto_increment
        primary key,
    is_delete      tinyint  default 0                 not null comment '是否删除状态，1：删除，0：有效',
    gmt_modified   datetime default CURRENT_TIMESTAMP not null comment '创建时间',
    gmt_create     datetime default CURRENT_TIMESTAMP not null comment '最后更新时间',
    interface_type tinyint                            not null comment '请求接口类型:1 出库单查询，2 旺店通订单查询，3 原始订单查询',
    start          datetime                           not null comment '查询起始时间',
    end            datetime                           not null comment '查询结束时间',
    status         tinyint                            not null comment '本次请求状态:1 成功，0 失败',
    total_count    int                                not null comment '响应数据总记录数量',
    page_no        int                                not null comment '当前请求页数',
    actual_size    int                                not null comment '当前请求实际返回数据条数',
    remark         varchar(1000)                      null comment '备注'
)
    comment '旺店通数据采集日志记录' charset = utf8;

create table wdt_refund_order_goods
(
    id           bigint auto_increment comment '主键'
        primary key,
    rec_id       int            null comment '旺店通主键',
    refund_id    int            null comment '退换单主键id',
    target_type  int            null comment '商品类型 1表示单品2表示组合装',
    target_id    int            null comment '组合装或者单品的id',
    goods_name   varchar(255)   null comment '商品名称',
    spec_name    varchar(255)   null comment '规格名称',
    merchant_no  varchar(40)    null comment '代表单品(sku)所有属性的唯一编码，用于系统单品区分',
    retail_price decimal(20, 4) null comment '零售价',
    num          decimal(20, 4) null comment '数量',
    remark       varchar(255)   null comment '备注',
    spec_code    varchar(40)    null comment '规格编码',
    is_sn_enable int            null comment '默认为''0''，0不启用序列号 1强序列号 2弱序列号',
    oid          varchar(40)    null comment '原始子订单编号',
    created      datetime       null comment '创建时间',
    modified     datetime       null comment '最后修改时间',
    brand_name   varchar(64)    null comment '品牌名称',
    barcode      varchar(50)    null comment '主条码'
)
    comment '换出货品信息列表';

create table wdt_user_fenxiao
(
    id          bigint auto_increment comment '主键id'
        primary key,
    fenxiao_id  varchar(40)                                                      null comment '分销商id',
    platform_id bigint                                                           null comment '平台id',
    shop_id     bigint                                                           not null comment '店铺id',
    user_id     bigint                                                           not null comment '用户id',
    tenant_id   bigint                                 default 0                 not null comment '租户编号',
    creator     varchar(64) collate utf8mb4_unicode_ci default ''                null comment '创建者',
    create_time datetime                               default CURRENT_TIMESTAMP not null comment '创建时间',
    updater     varchar(64) collate utf8mb4_unicode_ci default ''                null comment '更新者',
    update_time datetime                               default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    deleted     bit                                    default b'0'              not null comment '是否删除'
)
    comment '用户分销商关联表';

create table wdt_shop_fenxiao
(
    id           bigint auto_increment comment '主键id'
        primary key,
    fenxiao_id   varchar(40) charset utf8                                         not null comment '分销商id',
    fenxiao_name varchar(140) charset utf8                                        null comment '分销商名称',
    shop_id      bigint                                                           not null comment '店铺id',
    platform_id  bigint                                                           not null comment '平台id',
    tenant_id    bigint                                 default 0                 not null comment '租户编号',
    creator      varchar(64) collate utf8mb4_unicode_ci default ''                null comment '创建者',
    create_time  datetime                               default CURRENT_TIMESTAMP not null comment '创建时间',
    updater      varchar(64) collate utf8mb4_unicode_ci default ''                null comment '更新者',
    update_time  datetime                               default CURRENT_TIMESTAMP not null on update CURRENT_TIMESTAMP comment '更新时间',
    deleted      bit                                    default b'0'              not null comment '是否删除'
)
    comment '店铺分销商关联表';